module.exports = {
  languages: ['en', 'fa', 'ar', 'de'],
  Products: {
    cms: {
      en: {
        '@context': 'https://schema.org',
        brand: {
          name: 'aasaam',
          description: 'aasaam software development group',
        },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/cms.svg',
        image: 'https://aasaam.com/logo/cms.svg',
        name: 'CMS',
        description: 'Content Management System',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/en/products/cms',
        },
      },
      fa: {
        '@context': 'https://schema.org',
        brand: { name: 'آسام', description: 'گروه نرم‌افزاری آسام' },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/cms.svg',
        image: 'https://aasaam.com/logo/cms.svg',
        name: 'CMS',
        description: 'سامانه مدیریت محتوا',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/fa/products/cms',
        },
      },
    },
    dns: {
      en: {
        '@context': 'https://schema.org',
        brand: {
          name: 'aasaam',
          description: 'aasaam software development group',
        },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/dns.svg',
        image: 'https://aasaam.com/logo/dns.svg',
        name: 'DNS',
        description: 'Domain Name System',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/en/products/dns',
        },
      },
      fa: {
        '@context': 'https://schema.org',
        brand: { name: 'آسام', description: 'گروه نرم‌افزاری آسام' },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/dns.svg',
        image: 'https://aasaam.com/logo/dns.svg',
        name: 'DNS',
        description: 'سامانه نام دامنه',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/fa/products/dns',
        },
      },
    },
    email: {
      en: {
        '@context': 'https://schema.org',
        brand: {
          name: 'aasaam',
          description: 'aasaam software development group',
        },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/email.svg',
        image: 'https://aasaam.com/logo/email.svg',
        name: 'EMail',
        description: 'EMail Management',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/en/products/dns',
        },
      },
      fa: {
        '@context': 'https://schema.org',
        brand: { name: 'آسام', description: 'گروه نرم‌افزاری آسام' },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/email.svg',
        image: 'https://aasaam.com/logo/email.svg',
        name: 'EMail',
        description: 'سامانه مدیریت ایمیل',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/fa/products/email',
        },
      },
    },
    htm: {
      en: {
        '@context': 'https://schema.org',
        brand: {
          name: 'aasaam',
          description: 'aasaam software development group',
        },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/htm.svg',
        image: 'https://aasaam.com/logo/htm.svg',
        name: 'HTM',
        description: 'HTTP Traffic Manager',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/en/products/htm',
        },
      },
      fa: {
        '@context': 'https://schema.org',
        brand: { name: 'آسام', description: 'گروه نرم‌افزاری آسام' },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/htm.svg',
        image: 'https://aasaam.com/logo/htm.svg',
        name: 'HTM',
        description: 'سامانه مدیریت ترافیک HTTP',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/fa/products/htm',
        },
      },
    },
    sita: {
      en: {
        '@context': 'https://schema.org',
        brand: {
          name: 'aasaam',
          description: 'aasaam software development group',
        },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/sita.svg',
        image: 'https://aasaam.com/logo/sita.svg',
        name: 'Sita',
        description: 'aasaam central advertisement management',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/en/products/dns',
        },
      },
      fa: {
        '@context': 'https://schema.org',
        brand: { name: 'آسام', description: 'گروه نرم‌افزاری آسام' },
        '@type': 'Product',
        logo: 'https://aasaam.com/logo/sita.svg',
        image: 'https://aasaam.com/logo/sita.svg',
        name: 'سیتا',
        description: 'سامانه یکپارچه تبلیغات آسام',
        offers: {
          '@type': 'Demand',
          availability: 'https://schema.org/OnlineOnly',
          url: 'https://aasaam.com/fa/products/sita',
        },
      },
    },
  },
  Organization: {
    en: {
      '@type': 'Organization',
      description: 'aasaam software development group',
      name: 'aasaam',
      url: 'https://aasaam.com/',
      logo: 'https://aasaam.com/logo.svg',
      email: 'info@aasaam.com',
      telephone: ['+982191008212'],
      foundingDate: '2014-10-14',
      legalName: 'Dadeh Pardazan Ati Prozheh',
      identifier: [
        {
          '@type': 'PropertyValue',
          name: 'nationalIdentifier',
          value: '14004466417',
        },
        {
          '@type': 'PropertyValue',
          name: 'economicCode',
          value: '411475145475',
        },
        { '@type': 'PropertyValue', name: 'registerNumber', value: '461864' },
      ],
      mainEntityOfPage: {
        '@type': 'CreativeWork',
        keywords:
          'Content management system (CMS), Web Development, Site Reliability Engineering (SRE), DevOps, Security, Performance, Monitoring, IoT',
      },
      location: {
        '@type': 'Place',
        additionalProperty: {
          '@type': 'PropertyValue',
          name: 'ISO3166-2',
          value: 'IR-07',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 35.7235195,
          longitude: 51.3966331,
        },
      },
      address: {
        '@type': 'PostalAddress',
        addressCountry: 'IR',
        addressRegion: 'Tehran',
        postalCode: '1413954311',
        addressLocality: 'No 3, West 2nd St, Mordad St, District 6',
      },
      contactPoint: [
        {
          '@type': 'ContactPoint',
          contactType: 'information',
          email: 'info@aasaam.com',
          telephone: '+982191008212',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'sales',
          email: 'sales@aasaam.com',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'support',
          email: 'support@aasaam.com',
        },
      ],
      sameAs: [
        'https://github.com/aasaam/',
        'https://gitlab.com/aasaam/',
        'https://twitter.com/aasaaminfo/',
        'https://t.me/aasaaminfo/',
        'https://www.instagram.com/aasaaminfo/',
        'https://www.facebook.com/aasaaminfo/',
        'https://www.linkedin.com/company/aasaam/',
        'https://medium.com/@aasaaminfo/',
        'https://www.youtube.com/channel/UCHenb52NxQqHaD7ojibBEEg/',
        'https://virgool.io/@aasaaminfo/',
        'https://www.aparat.com/aasaaminfo/',
      ],
      '@context': 'https://schema.org',
    },
    fa: {
      '@type': 'Organization',
      description: 'گروه نرم‌افزاری آسام',
      name: 'آسام',
      url: 'https://aasaam.com/',
      logo: 'https://aasaam.com/logo.svg',
      email: 'info@aasaam.com',
      telephone: ['+982191008212'],
      foundingDate: '2014-10-14',
      legalName: 'داده پردازان آتی‌پروژه',
      identifier: [
        {
          '@type': 'PropertyValue',
          name: 'nationalIdentifier',
          value: '14004466417',
        },
        {
          '@type': 'PropertyValue',
          name: 'economicCode',
          value: '411475145475',
        },
        { '@type': 'PropertyValue', name: 'registerNumber', value: '461864' },
      ],
      mainEntityOfPage: {
        '@type': 'CreativeWork',
        keywords:
          'Content management system (CMS), Web Development, Site Reliability Engineering (SRE), DevOps, Security, Performance, Monitoring, IoT, سامانه مدیریت محتوا, مونیتورینگ, طراحی سایت خبری, طراحی سایت خبری, طراحی سایت روزنامه, توسعه وب, طراحی وب, دواپس, توسعه عملیات, مهندسی پایداری وب, امنیت, اینترنت اشیاء',
      },
      location: {
        '@type': 'Place',
        additionalProperty: {
          '@type': 'PropertyValue',
          name: 'ISO3166-2',
          value: 'IR-07',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 35.7235195,
          longitude: 51.3966331,
        },
      },
      address: {
        '@type': 'PostalAddress',
        addressCountry: 'IR',
        addressRegion: 'تهران',
        postalCode: '1413954311',
        addressLocality: 'منطقه ۶، گلها، خیابان مرداد، خیابان دوم غربی، پلاک ۳',
      },
      contactPoint: [
        {
          '@type': 'ContactPoint',
          contactType: 'information',
          email: 'info@aasaam.com',
          telephone: '+982191008212',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'sales',
          email: 'sales@aasaam.com',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'support',
          email: 'support@aasaam.com',
        },
      ],
      sameAs: [
        'https://github.com/aasaam/',
        'https://gitlab.com/aasaam/',
        'https://twitter.com/aasaaminfo/',
        'https://t.me/aasaaminfo/',
        'https://www.instagram.com/aasaaminfo/',
        'https://www.facebook.com/aasaaminfo/',
        'https://www.linkedin.com/company/aasaam/',
        'https://medium.com/@aasaaminfo/',
        'https://www.youtube.com/channel/UCHenb52NxQqHaD7ojibBEEg/',
        'https://virgool.io/@aasaaminfo/',
        'https://www.aparat.com/aasaaminfo/',
      ],
      '@context': 'https://schema.org',
    },
    ar: {
      '@type': 'Organization',
      description: 'مجموعة برامج آسام',
      name: 'آسام',
      url: 'https://aasaam.com/',
      logo: 'https://aasaam.com/logo.svg',
      email: 'info@aasaam.com',
      telephone: ['+982191008212'],
      foundingDate: '2014-10-14',
      legalName: 'داده فردازان آتي‌فروجه',
      identifier: [
        {
          '@type': 'PropertyValue',
          name: 'nationalIdentifier',
          value: '14004466417',
        },
        {
          '@type': 'PropertyValue',
          name: 'economicCode',
          value: '411475145475',
        },
        { '@type': 'PropertyValue', name: 'registerNumber', value: '461864' },
      ],
      mainEntityOfPage: {
        '@type': 'CreativeWork',
        keywords:
          'Content management system (CMS), Web Development, Site Reliability Engineering (SRE), DevOps, Security, Performance, Monitoring, IoT, نظام إدارة المحتوى, وكالة أنباء, صحيفة, تطوير ويب, ديف أوبس, الأمان, أداء, إنترنت الأشياء',
      },
      location: {
        '@type': 'Place',
        additionalProperty: {
          '@type': 'PropertyValue',
          name: 'ISO3166-2',
          value: 'IR-07',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 35.7235195,
          longitude: 51.3966331,
        },
      },
      address: {
        '@type': 'PostalAddress',
        addressCountry: 'IR',
        addressRegion: 'طهران',
        postalCode: '1413954311',
        addressLocality: 'منطقة ٦، شارع مرداد، الشارع الثاني الغربي، رقم ۳',
      },
      contactPoint: [
        {
          '@type': 'ContactPoint',
          contactType: 'information',
          email: 'info@aasaam.com',
          telephone: '+982191008212',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'sales',
          email: 'sales@aasaam.com',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'support',
          email: 'support@aasaam.com',
        },
      ],
      sameAs: [
        'https://github.com/aasaam/',
        'https://gitlab.com/aasaam/',
        'https://twitter.com/aasaaminfo/',
        'https://t.me/aasaaminfo/',
        'https://www.instagram.com/aasaaminfo/',
        'https://www.facebook.com/aasaaminfo/',
        'https://www.linkedin.com/company/aasaam/',
        'https://medium.com/@aasaaminfo/',
        'https://www.youtube.com/channel/UCHenb52NxQqHaD7ojibBEEg/',
        'https://virgool.io/@aasaaminfo/',
        'https://www.aparat.com/aasaaminfo/',
      ],
      '@context': 'https://schema.org',
    },
    de: {
      '@type': 'Organization',
      description: 'aasaam software development group',
      name: 'aasaam',
      url: 'https://aasaam.com/',
      logo: 'https://aasaam.com/logo.svg',
      email: 'info@aasaam.com',
      telephone: ['+982191008212'],
      foundingDate: '2014-10-14',
      legalName: 'Dadeh Pardazan Ati Prozheh',
      identifier: [
        {
          '@type': 'PropertyValue',
          name: 'nationalIdentifier',
          value: '14004466417',
        },
        {
          '@type': 'PropertyValue',
          name: 'economicCode',
          value: '411475145475',
        },
        { '@type': 'PropertyValue', name: 'registerNumber', value: '461864' },
      ],
      mainEntityOfPage: {
        '@type': 'CreativeWork',
        keywords:
          'Content management system (CMS), Web Development, Site Reliability Engineering (SRE), DevOps, Security, Performance, Monitoring, IoT, Webentwicklung, Sicherheit',
      },
      location: {
        '@type': 'Place',
        additionalProperty: {
          '@type': 'PropertyValue',
          name: 'ISO3166-2',
          value: 'IR-07',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 35.7235195,
          longitude: 51.3966331,
        },
      },
      address: {
        '@type': 'PostalAddress',
        addressCountry: 'IR',
        addressRegion: 'Teheran',
        postalCode: '1413954311',
        addressLocality: 'Nummer 3, West 2. Straße, Mordad-Straße, Bezirk 6',
      },
      contactPoint: [
        {
          '@type': 'ContactPoint',
          contactType: 'information',
          email: 'info@aasaam.com',
          telephone: '+982191008212',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'sales',
          email: 'sales@aasaam.com',
        },
        {
          '@type': 'ContactPoint',
          contactType: 'support',
          email: 'support@aasaam.com',
        },
      ],
      sameAs: [
        'https://github.com/aasaam/',
        'https://gitlab.com/aasaam/',
        'https://twitter.com/aasaaminfo/',
        'https://t.me/aasaaminfo/',
        'https://www.instagram.com/aasaaminfo/',
        'https://www.facebook.com/aasaaminfo/',
        'https://www.linkedin.com/company/aasaam/',
        'https://medium.com/@aasaaminfo/',
        'https://www.youtube.com/channel/UCHenb52NxQqHaD7ojibBEEg/',
        'https://virgool.io/@aasaaminfo/',
        'https://www.aparat.com/aasaaminfo/',
      ],
      '@context': 'https://schema.org',
    },
  },
};
